// TEMPORARY DATA

export let role = "admin";

export const teachersData = [
  {
    id: 1,
    teacherId: "T001",
    name: "Juan Gómez",
    email: "juan.gomez@vocali.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Inglés", "Geometry"],
    classes: ["1B", "2A", "3C"],
    address: "Calle 25 Norte, San Matías, Pue.",
  },
  {
    id: 2,
    teacherId: "T002",
    name: "Elena Gómez",
    email: "elena.gomez@vocali.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Chino", "Francés"],
    classes: ["5A", "4B", "3C"],
    address: "Calle 25 Norte, San Matías, Pue.",
  },
  {
    id: 3,
    teacherId: "T003",
    name: "Miguel Rodríguez",
    email: "miguel.rodriguez@vocali.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Alemán"],
    classes: ["5A", "4B", "3C"],
    address: "Calle 25 Norte, San Matías, Pue.",
  },
  {
    id: 4,
    teacherId: "T004",
    name: "Javier Fernández",
    email: "javier.fernandez@vocali.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Inglés"],
    classes: ["5A", "4B", "3C"],
    address: "Calle 25 Norte, San Matías, Pue.",
  },
  {
    id: 5,
    teacherId: "T005",
    name: "Juana Ramírez",
    email: "juana.ramirez@vocali.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Alemán", "Inglés"],
    classes: ["5A", "4B", "3C"],
    address: "Calle 25 Norte, San Matías, Pue.",
  },
  {
    id: 6,
    teacherId: "T006",
    name: "Ana Santiago",
    email: "ana.santiago@vocali.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Chino"],
    classes: ["5A", "4B", "3C"],
    address: "Calle 25 Norte, San Matías, Pue.",
  },
  {
    id: 7,
    teacherId: "T007",
    name: "Alberto Blanco",
    email: "alberto.blanco@vocali.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Español", "Spanish"],
    classes: ["5A", "4B", "3C"],
    address: "Calle 25 Norte, San Matías, Pue.",
  },
  {
    id: 8,
    teacherId: "T008",
    name: "Ofelia Castro",
    email: "ofelia.castro@vocali.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Inglés", "Geometry"],
    classes: ["5A", "4B", "3C"],
    address: "Calle 25 Norte, San Matías, Pue.",
  },
  {
    id: 9,
    teacherId: "T009",
    name: "Diego Beltrán",
    email: "derek@vocali.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Español", "Español"],
    classes: ["5A", "4B", "3C"],
    address: "Calle 25 Norte, San Matías, Pue.",
  },
  {
    id: 10,
    teacherId: "T010",
    name: "Juan Herrera",
    email: "juan.herrera@vocali.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Alemán"],
    classes: ["5A", "4B", "3C"],
    address: "Calle 25 Norte, San Matías, Pue.",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "V001",
    name: "Juan Gómez",
    email: "juan.gomez@vocali.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "1B",
    address: "Calle 25 Norte, San Matías, Pue.",
  },
  {
    id: 2,
    studentId: "V002",
    name: "Elena Gómez",
    email: "elena.gomez@vocali.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Calle 25 Norte, San Matías, Pue.",
  },
  {
    id: 3,
    studentId: "V003",
    name: "Miguel Rodríguez",
    email: "miguel.rodriguez@vocali.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Calle 25 Norte, San Matías, Pue.",
  },
  {
    id: 4,
    studentId: "V004",
    name: "Javier Fernández",
    email: "javier.fernandez@vocali.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Calle 25 Norte, San Matías, Pue.",
  },
  {
    id: 5,
    studentId: "V005",
    name: "Juana Ramírez",
    email: "juana.ramirez@vocali.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Calle 25 Norte, San Matías, Pue.",
  },
  {
    id: 6,
    studentId: "V006",
    name: "Ana Santiago",
    email: "ana.santiago@vocali.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Calle 25 Norte, San Matías, Pue.",
  },
  {
    id: 7,
    studentId: "V007",
    name: "Alberto Blanco",
    email: "alberto.blanco@vocali.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Calle 25 Norte, San Matías, Pue.",
  },
  {
    id: 8,
    studentId: "V008",
    name: "Ofelia Castro",
    email: "ofelia.castro@vocali.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Calle 25 Norte, San Matías, Pue.",
  },
  {
    id: 9,
    studentId: "V009",
    name: "Diego Beltrán",
    email: "derek@vocali.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Calle 25 Norte, San Matías, Pue.",
  },
  {
    id: 10,
    studentId: "V010",
    name: "Juan Herrera",
    email: "juan.herrera@vocali.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Calle 25 Norte, San Matías, Pue.",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "Juan Gómez",
    students: ["Sara Barajas"],
    email: "juan.gomez@vocali.com",
    phone: "1234567890",
    address: "Calle 25 Norte, San Matías, Pue.",
  },
  {
    id: 2,
    name: "Elena Gómez",
    students: ["Cecilia Beltrán"],
    email: "elena.gomez@vocali.com",
    phone: "1234567890",
    address: "Calle 25 Norte, San Matías, Pue.",
  },
  {
    id: 3,
    name: "Miguel Rodríguez",
    students: ["Estefanía Calderón"],
    email: "miguel.rodriguez@vocali.com",
    phone: "1234567890",
    address: "Calle 25 Norte, San Matías, Pue.",
  },
  {
    id: 4,
    name: "Javier Fernández",
    students: ["Amalia Flores", "Iván Bravo"],
    email: "miguel.rodriguez@vocali.com",
    phone: "1234567890",
    address: "Calle 25 Norte, San Matías, Pue.",
  },
  {
    id: 5,
    name: "Juana Ramírez",
    students: ["Mabel Herrera"],
    email: "miguel.rodriguez@vocali.com",
    phone: "1234567890",
    address: "Calle 25 Norte, San Matías, Pue.",
  },
  {
    id: 6,
    name: "Ana Santiago",
    students: ["Joel Lira"],
    email: "miguel.rodriguez@vocali.com",
    phone: "1234567890",
    address: "Calle 25 Norte, San Matías, Pue.",
  },
  {
    id: 7,
    name: "Alberto Blanco",
    students: ["Karla Torres", "Liliana Uribe"],
    email: "miguel.rodriguez@vocali.com",
    phone: "1234567890",
    address: "Calle 25 Norte, San Matías, Pue.",
  },
  {
    id: 8,
    name: "Ofelia Castro",
    students: ["Alejandro Becerra"],
    email: "miguel.rodriguez@vocali.com",
    phone: "1234567890",
    address: "Calle 25 Norte, San Matías, Pue.",
  },
  {
    id: 9,
    name: "Diego Beltrán",
    students: ["Susana Vega", "Matilde Soto"],
    email: "miguel.rodriguez@vocali.com",
    phone: "1234567890",
    address: "Calle 25 Norte, San Matías, Pue.",
  },
  {
    id: 10,
    name: "Juan Herrera",
    students: ["Estela Soler"],
    email: "miguel.rodriguez@vocali.com",
    phone: "1234567890",
    address: "Calle 25 Norte, San Matías, Pue.",
  },
];

export const subjectsData = [
  {
    id: 1,
    name: "Español",
    teachers: ["Javier Fernández", "Ana Santiago"],
  },
  {
    id: 2,
    name: "Inglés",
    teachers: ["Juan Gómez", "Juana Ramírez", "Ofelia Castro"],
  },
  {
    id: 3,
    name: "Chino",
    teachers: ["Diego Beltrán", "Alberto Blanco"],
  },
  {
    id: 4,
    name: "Francés",
    teachers: ["Miguel Rodríguez", "Juan Herrera"],
  },
  {
    id: 5,
    name: "Alemán",
    teachers: ["Ofelia Castro", "Alberto Blanco"],
  },
  {
    id: 6,
    name: "Inglés",
    teachers: ["Juan Gómez", "Juana Ramírez"],
  },
  {
    id: 7,
    name: "Francés",
    teachers: ["Miguel Rodríguez", "Juan Herrera"],
  },
  {
    id: 8,
    name: "Chino",
    teachers: ["Diego Beltrán", "Alberto Blanco"],
  },
  {
    id: 9,
    name: "Alemán",
    teachers: ["Ofelia Castro"],
  },
  {
    id: 10,
    name: "Español",
    teachers: ["Javier Fernández", "Ana Santiago"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Juan Gómez",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Elena Gómez",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Miguel Rodríguez",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Javier Fernández",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Juana Ramírez",
  },
  {
    id: 5,
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Ana Santiago",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Alberto Blanco",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Ofelia Castro",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Diego Beltrán",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Juan Herrera",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Inglés",
    class: "1A",
    teacher: "Juan Gómez",
  },
  {
    id: 2,
    subject: "Español",
    class: "2A",
    teacher: "Elena Gómez",
  },
  {
    id: 3,
    subject: "Chino",
    class: "3A",
    teacher: "Miguel Rodríguez",
  },
  {
    id: 4,
    subject: "Alemán",
    class: "1B",
    teacher: "Javier Fernández",
  },
  {
    id: 5,
    subject: "Chino",
    class: "4A",
    teacher: "Juana Ramírez",
  },
  {
    id: 6,
    subject: "Alemán",
    class: "5A",
    teacher: "Ana Santiago",
  },
  {
    id: 7,
    subject: "Inglés",
    class: "6A",
    teacher: "Alberto Blanco",
  },
  {
    id: 8,
    subject: "Francés",
    class: "6B",
    teacher: "Ofelia Castro",
  },
  {
    id: 9,
    subject: "Chino",
    class: "6C",
    teacher: "Diego Beltrán",
  },
  {
    id: 10,
    subject: "Francés",
    class: "4B",
    teacher: "Juan Herrera",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Inglés",
    class: "1A",
    teacher: "Juan Gómez",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "Español",
    class: "2A",
    teacher: "Elena Gómez",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Chino",
    class: "3A",
    teacher: "Miguel Rodríguez",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Alemán",
    class: "1B",
    teacher: "Javier Fernández",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Chino",
    class: "4A",
    teacher: "Mabelle Wallace",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Alemán",
    class: "5A",
    teacher: "Dale Thompson",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "Inglés",
    class: "6A",
    teacher: "Allie Conner",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Francés",
    class: "6B",
    teacher: "Hunter Fuller",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Chino",
    class: "7A",
    teacher: "Lois Lindsey",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Francés",
    class: "8A",
    teacher: "Vera Soto",
    date: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Inglés",
    class: "1A",
    teacher: "Anthony Boone",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "Español",
    class: "2A",
    teacher: "Clifford Bowen",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Chino",
    class: "3A",
    teacher: "Catherine Malone",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "Alemán",
    class: "1B",
    teacher: "Willie Medina",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Chino",
    class: "4A",
    teacher: "Jose Ruiz",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Alemán",
    class: "5A",
    teacher: "Katharine Owens",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "Inglés",
    class: "6A",
    teacher: "Shawn Norman",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Francés",
    class: "6B",
    teacher: "Don Holloway",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Chino",
    class: "7A",
    teacher: "Franklin Gregory",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Francés",
    class: "8A",
    teacher: "Danny Nguyen",
    dueDate: "2025-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Inglés",
    class: "1A",
    teacher: "Juan Gómez",
    student: "Juan Gómez",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "Español",
    class: "2A",
    teacher: "Juan Gómez",
    student: "Juan Gómez",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Chino",
    class: "3A",
    teacher: "Juan Gómez",
    student: "Juan Gómez",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    subject: "Alemán",
    class: "1B",
    teacher: "Juan Gómez",
    student: "Juan Gómez",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 5,
    subject: "Chino",
    class: "4A",
    teacher: "Juan Gómez",
    student: "Juan Gómez",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 6,
    subject: "Alemán",
    class: "5A",
    teacher: "Juan Gómez",
    student: "Juan Gómez",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 7,
    subject: "Inglés",
    class: "6A",
    teacher: "Juan Gómez",
    student: "Juan Gómez",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 8,
    subject: "Francés",
    class: "6B",
    teacher: "Juan Gómez",
    student: "Juan Gómez",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    subject: "Chino",
    class: "7A",
    teacher: "Juan Gómez",
    student: "Juan Gómez",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Francés",
    class: "8A",
    teacher: "Juan Gómez",
    student: "Juan Gómez",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Viaje al Lago",
    class: "1A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Día de Campo",
    class: "2A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Excursión a la Playa",
    class: "3A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Visita al Museo",
    class: "4A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Concierto de Música",
    class: "5A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Show de Magia",
    class: "1B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Viaje al Lago",
    class: "2B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Carrera de Ciclismo",
    class: "3B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Exposición de Arte",
    class: "4B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Torneo Deportivo",
    class: "5B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "Sobre Examen de Nivel 4A",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "Sobre Examen de Nivel 3A",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "Sobre Examen de Nivel 3B",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "Sobre Examen de Nivel 6A",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "Sobre Examen de Nivel 8C",
    class: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "Sobre Examen de Nivel 2A",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "Sobre Examen de Nivel 4C",
    class: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "Sobre Examen de Nivel 4B",
    class: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "Sobre Examen de Nivel 3C",
    class: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "Sobre Examen de Nivel 1C",
    class: "1C",
    date: "2025-01-01",
  },
];


// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export const calendarEvents = [
  {
    title: "Inglés",
    allDay: false,
    start: new Date(2024, 7, 12, 8, 0),
    end: new Date(2024, 7, 12, 8, 45),
  },
  {
    title: "Español",
    allDay: false,
    start: new Date(2024, 7, 12, 9, 0),
    end: new Date(2024, 7, 12, 9, 45),
  },
  {
    title: "Alemán",
    allDay: false,
    start: new Date(2024, 7, 12, 10, 0),
    end: new Date(2024, 7, 12, 10, 45),
  },
  {
    title: "Chino",
    allDay: false,
    start: new Date(2024, 7, 12, 11, 0),
    end: new Date(2024, 7, 12, 11, 45),
  },
  {
    title: "Francés",
    allDay: false,
    start: new Date(2024, 7, 12, 13, 0),
    end: new Date(2024, 7, 12, 13, 45),
  },
  {
    title: "Inglés",
    allDay: false,
    start: new Date(2024, 7, 12, 14, 0),
    end: new Date(2024, 7, 12, 14, 45),
  },
  {
    title: "Español",
    allDay: false,
    start: new Date(2024, 7, 13, 9, 0),
    end: new Date(2024, 7, 13, 9, 45),
  },
  {
    title: "Alemán",
    allDay: false,
    start: new Date(2024, 7, 13, 10, 0),
    end: new Date(2024, 7, 13, 10, 45),
  },
  {
    title: "Chino",
    allDay: false,
    start: new Date(2024, 7, 13, 11, 0),
    end: new Date(2024, 7, 13, 11, 45),
  },

  {
    title: "Inglés",
    allDay: false,
    start: new Date(2024, 7, 13, 14, 0),
    end: new Date(2024, 7, 13, 14, 45),
  },
  {
    title: "Inglés",
    allDay: false,
    start: new Date(2024, 7, 14, 8, 0),
    end: new Date(2024, 7, 14, 8, 45),
  },
  {
    title: "Alemán",
    allDay: false,
    start: new Date(2024, 7, 14, 10, 0),
    end: new Date(2024, 7, 14, 10, 45),
  },

  {
    title: "Francés",
    allDay: false,
    start: new Date(2024, 7, 14, 13, 0),
    end: new Date(2024, 7, 14, 13, 45),
  },
  {
    title: "Inglés",
    allDay: false,
    start: new Date(2024, 7, 14, 14, 0),
    end: new Date(2024, 7, 13, 14, 45),
  },
  {
    title: "Español",
    allDay: false,
    start: new Date(2024, 7, 15, 9, 0),
    end: new Date(2024, 7, 15, 9, 45),
  },
  {
    title: "Alemán",
    allDay: false,
    start: new Date(2024, 7, 15, 10, 0),
    end: new Date(2024, 7, 15, 10, 45),
  },
  {
    title: "Chino",
    allDay: false,
    start: new Date(2024, 7, 15, 11, 0),
    end: new Date(2024, 7, 15, 11, 45),
  },

  {
    title: "Inglés",
    allDay: false,
    start: new Date(2024, 7, 15, 14, 0),
    end: new Date(2024, 7, 15, 14, 45),
  },
  {
    title: "Inglés",
    allDay: false,
    start: new Date(2024, 7, 16, 8, 0),
    end: new Date(2024, 7, 16, 8, 45),
  },
  {
    title: "Español",
    allDay: false,
    start: new Date(2024, 7, 16, 9, 0),
    end: new Date(2024, 7, 16, 9, 45),
  },

  {
    title: "Chino",
    allDay: false,
    start: new Date(2024, 7, 16, 11, 0),
    end: new Date(2024, 7, 16, 11, 45),
  },
  {
    title: "Francés",
    allDay: false,
    start: new Date(2024, 7, 16, 13, 0),
    end: new Date(2024, 7, 16, 13, 45),
  },
  {
    title: "Inglés",
    allDay: false,
    start: new Date(2024, 7, 16, 14, 0),
    end: new Date(2024, 7, 16, 14, 45),
  },
];

export const paymentsData = [
  {
    id: 1,
    student: "Alicia Sánchez",
    amount: 1500,
    hours: 0,
    type: "Mensual",
    status: "Pagado",
    dueDate: "2026-06-05",
    paymentDate: "2026-06-03",
    method: "Transferencia",
  },
  {
    id: 2,
    student: "Roberto Juárez",
    amount: 800,
    hours: 8,
    type: "Por horas",
    status: "Pendiente",
    dueDate: "2026-06-10",
    paymentDate: "",
    method: "",
  },
  {
    id: 3,
    student: "Carlos Moreno",
    amount: 5000,
    hours: 0,
    type: "Curso completo",
    status: "Pagado",
    dueDate: "2026-06-01",
    paymentDate: "2026-05-28",
    method: "Tarjeta",
  },
  {
    id: 4,
    student: "Diana Pérez",
    amount: 1200,
    hours: 0,
    type: "Mensual",
    status: "Atrasado",
    dueDate: "2026-06-05",
    paymentDate: "",
    method: "",
  },
  {
    id: 5,
    student: "Esteban Rubio",
    amount: 600,
    hours: 6,
    type: "Por horas",
    status: "Pagado",
    dueDate: "2026-06-12",
    paymentDate: "2026-06-12",
    method: "Efectivo",
  },
];

export const teacherPaymentsData = [
  {
    id: 1,
    teacher: "Juan Gómez",
    amount: 3200,
    type: "Pago por Horas",
    hours: 32,
    status: "Pagado",
    paymentDate: "2026-06-15",
    method: "Transferencia",
  },
  {
    id: 2,
    teacher: "Elena Gómez",
    amount: 5000,
    type: "Sueldo Fijo",
    hours: 0,
    status: "Pagado",
    paymentDate: "2026-06-01",
    method: "Transferencia",
  },
  {
    id: 3,
    teacher: "Miguel Rodríguez",
    amount: 1800,
    type: "Pago por Horas",
    hours: 18,
    status: "Pendiente",
    paymentDate: "",
    method: "",
  },
  {
    id: 4,
    teacher: "Javier Fernández",
    amount: 4800,
    type: "Sueldo Fijo",
    hours: 0,
    status: "Pagado",
    paymentDate: "2026-06-01",
    method: "Transferencia",
  },
  {
    id: 5,
    teacher: "Ofelia Castro",
    amount: 2500,
    type: "Pago por Horas",
    hours: 25,
    status: "Pendiente",
    paymentDate: "",
    method: "",
  },
];